# Generated by Django 4.0.2 on 2022-02-26 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_customuser_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='media_path',
            field=models.ImageField(upload_to='post_pictures'),
        ),
    ]
